version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      # Auth AWS
      - echo Authenticating into AWS ECR...
      - aws configure set region eu-central-1
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 540876827424.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Listing contents of the current directory
      - ls -alh
      - echo Displaying Docker version
      - docker --version
      - echo Building shtifh-admin-server Image
      - docker build -t shtifh-admin-server -f ./apps/shtifh/admin/server/Dockerfile .
      - echo Tagging shtifh-admin-server
      - docker tag shtifh-admin-server:latest 540876827424.dkr.ecr.us-east-1.amazonaws.com/shtifh-admin-server:latest

  post_build:
    commands:
      - echo Pushing Shtifh Server image...
      - docker push 540876827424.dkr.ecr.us-east-1.amazonaws.com/shtifh-admin-server:latest

artifacts:
  files:
    - imagedefinitions.json
